# Generated by Django 3.1.2 on 2020-10-31 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер телефона')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата объявления')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Изображения')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('status', models.CharField(choices=[('new', 'Новостройка'), ('secondhand', 'Вторичка')], max_length=20, verbose_name='Тип')),
                ('area', models.PositiveSmallIntegerField(default=0, verbose_name='Площадь')),
                ('floor', models.PositiveSmallIntegerField(default=0, verbose_name='Этаж')),
                ('year_of_flat', models.PositiveSmallIntegerField(default=1950, verbose_name='Год')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
