# Generated by Django 3.1.2 on 2020-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(upload_to='ads', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
