# Generated by Django 3.1.2 on 2020-11-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_advert_status_advert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='advert',
            old_name='status_advert',
            new_name='is_visible',
        ),
    ]
